services:
  db:
    image: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'

  nginx_1:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./site1:/var/www/html
      - ./.docker/nginx_1:/etc/nginx/conf.d
    depends_on:
      - php_1
      - node_1

  nginx_2:
    image: nginx:latest
    restart: always
    ports:
      - "81:80"
    volumes:
      - ./site2:/var/www/html
      - ./.docker/nginx_2:/etc/nginx/conf.d
    depends_on:
      - php_2
      - node_2

  composer_1:
    image: composer:2.4.3
    volumes:
      - ./site1:/app
    command:
      - install

  node_1:
    image: node:14.18.1
    volumes:
      - ./site1:/app
    working_dir: /app
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm run build

  composer_2:
    image: composer:2.4.3
    volumes:
      - ./site2:/app
    command:
      - install

  node_2:
    image: node:14.18.1
    volumes:
      - ./site2:/app
    working_dir: /app
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm run build

  php_1:
    restart: always
    build: ./.docker/php
    volumes:
      - ./site1:/var/www/html
    depends_on:
      - composer_1
      - db

  php_2:
    restart: always
    build: ./.docker/php
    volumes:
      - ./site2:/var/www/html
    depends_on:
      - composer_2
      - db

volumes:
    db_data: