services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'

  nginx_1:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./site1:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - php_1
      - node_1

  composer_1:
    image: composer:2.4.3
    volumes:
      - ./site1:/app
    command:
      - install

  node_1:
    image: node:14.18.1
    volumes:
      - ./site1:/app
    command:
      - build

  php_1:
    restart: always
    build: ./.docker/php
    volumes:
      - ./site1:/var/www/html
    depends_on:
      - composer_1
      - db

volumes:
    db_data: