FROM php:8.1-fpm

#WORKDIR /var/www/html

#RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

#RUN apt-get update && apt-get install -y nodejs npm

#RUN composer install
#RUN npm run build
#RUN php artisan key:generate
#RUN php artisan migrate:fresh --seed
